### ISSUE TITLE
As a homebuyer, I want to know the general availability of houses in an area.

### ISSUE THREAD

**Issue by ColtonFalkner** [ColtonFalkner/FutureMove#2]
- [x] break down zillow api/realtor and pull info 
- [x] geocoding service
- [x] put a map on the page of the area a person searches 

- [x] set limits on search area

**Comment by ShannenGrimes** [comment]
Hi Colton, we finally got Zillow to work.  Here is the script for address details: 

`  <script type="text/javascript">
   
        var settings = {
      "url": "http://www.zillow.com/webservice/GetSearchResults.htm?zws-id=X1-ZWz1hhp4ni0nij_52lx1&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA",
      "method": "POST",
      "headers": {
        "content-type": "application/json"
      },
    }
    $.ajax(settings).done(function (response) {
      console.log(response);
    });

// ---------------------------------------------------------
  </script>`
