### ISSUE TITLE
As a potential mover, I want to know more about the area I'm relocating to. 

### ISSUE THREAD

**Issue by ColtonFalkner** [ColtonFalkner/FutureMove#3]
- [x] decide what info (crime, schools, parks, venues, restaurants)
- [x] create divs to dynamically display information 
- [x] Create javascript to pass user city and state to school search
- [x] Display schools on html

**Comment by ShannenGrimes** [comment]
I will work on reading the documentation and adding the API.

**Comment by ShannenGrimes** [comment]
Here is a link to the API catalogue:  Governmentt API - http://catalog.data.gov/api/3/
Need to learn CKAN to use API:  https://docs.ckan.org/en/latest/api/index.h

**Comment by ShannenGrimes** [comment]
Crime:  https://catalog.data.gov/dataset/uniform-crime-reporting-ucr-program

**Comment by ShannenGrimes** [comment]
CRIME Details:
 `var crime = {
    "async": true,
    "crossDomain": true,
    "url": "https://api.gateway.attomdata.com/communityapi/v2.0.0/Area/Full/?AreaId=CO47037",
    "method": "GET",
    "headers": {
        "apikey" : "0da31fe50c76d41e8f480520b54d9a17",
        "accept": "application/json"
    }
}
$.ajax(crime).done(function (response) {
	console.log(response);
});
`

**Comment by ShannenGrimes** [comment]
![image](https://user-images.githubusercontent.com/54419873/69907462-685ceb00-139b-11ea-9c76-8128f486e262.png)
